---
- name: Create Centos VM from scratch
  hosts: localhost
  gather_facts: false
  vars:
    esxi_login: &esxi_login
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'   
      validate_certs: no 
    vm_login: &vm_login
      vm_username: "root"
      vm_password: '{{ vm_password_new }}'
      vm_id: '{{ vm_name }}'
    retry_settings: &retry_settings
      retries: 6
      delay: 10 
      register: result           
      until: result is succeeded       
  vars_files: 
    - vars-centos.yml
    - vars-esx.yml
  tasks: 
  - name: Add ESXi to Ansible Hosts for SSH
    add_host:
      name: '{{ esxi_address }}'
      group: "esx"
      ansible_user: '{{ esxi_username }}'
      ansible_password: '{{ esxi_password }}'
      ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  - name: Gather facts about ESXi Host services
    vmware_host_service_facts:
      <<: *esxi_login
      esxi_hostname: '{{ esxi_fqdn }}'
    delegate_to: localhost
    register: host_services
  - name: Enable ESX SSH (TSM-SSH)
    vmware_host_service_manager:
      <<: *esxi_login
      esxi_hostname: '{{ esxi_address }}'
      service_name: TSM-SSH
      state: present
    delegate_to: localhost
  - name: Enable ESX Shell (TSM)
    vmware_host_service_manager:
      <<: *esxi_login
      esxi_hostname: '{{ esxi_address }}'
      service_name: TSM
      state: present
    delegate_to: localhost
  - name: Download the Centos ISO
    shell: 'wget -P /vmfs/volumes/{{ esxi_datastore }} {{ centos_iso_url }}'
    args:
      creates: '/vmfs/volumes/{{ esxi_datastore }}/{{ centos_iso }}'
    delegate_to: '{{ esxi_address }}'
  - name: Download the config iso
    shell: 'wget -P /vmfs/volumes/{{ esxi_datastore }} {{ centos_config_iso_url }}'
    args:
      creates: '/vmfs/volumes/{{ esxi_datastore }}/{{ centos_config_iso }}'
    delegate_to: '{{ esxi_address }}'
  - name: Create a new VM
    vmware_guest:
      <<: *esxi_login
      folder: /
      name: '{{ vm_name }}'
      state: present
      guest_id: centos7_64Guest
      cdrom:
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: '[{{ esxi_datastore }}] {{ centos_iso }}'
          - controller_number: 0
            unit_number: 1
            state: present
            type: iso
            iso_path: '[{{ esxi_datastore }}] {{ centos_config_iso }}'
      disk:
      - size_gb: '{{ vm_disk_gb }}'
        type: thin
        datastore: '{{ esxi_datastore }}'
      hardware:
        memory_mb: '{{ vm_memory_mb }}'
        num_cpus: '{{ vm_num_cpus }}'
        scsi: lsilogicsas
      networks:
      - name: '{{ vm_network }}'
        device_type: e1000
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy_vm
  - name: Change virtual machine's boot order and related parameters
    vmware_guest_boot_manager:
      <<: *esxi_login 
      name: '{{ vm_name }}'
      boot_delay: 1000
      enter_bios_setup: False
      boot_retry_enabled: True
      boot_retry_delay: 20000
      boot_firmware: bios
      secure_boot_enabled: False
      boot_order:
        - disk
        - cdrom
        - ethernet
        - floppy
    delegate_to: localhost
    register: vm_boot_order
  - name: Restore original service states
    vmware_host_service_manager:
      <<: *esxi_login
      esxi_hostname: '{{ esxi_address }}'
      service_name: '{{ item.key }}'
      state: absent
    delegate_to: localhost
    loop: "{{ host_services['host_service_facts'][esxi_fqdn] }}"
    when: item.running|bool == false
  - name: Power-On the virtual machine
    vmware_guest_powerstate:
      <<: *esxi_login
      name: '{{ vm_name }}'
      state: powered-on
    delegate_to: localhost
    register: powerstate
  - name: Wait for VMware tools to become available 
    vmware_guest_tools_wait:
      <<: *esxi_login
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Test vmware_vm_shell
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      <<: *vm_login
      vm_password: '{{ vm_password_old }}'
      vm_shell: '/usr/bin/sh'
      vm_shell_args: '-c "echo hello"'
      wait_for_process: true
  - name: Set Hostname
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      <<: *vm_login
      vm_password: '{{ vm_password_old }}'
      vm_shell: '/usr/bin/sh'
      vm_shell_args: "-c \"hostnamectl set-hostname {{ vm_hostname }}.{{ vm_domain }}\""
      wait_for_process: true
  - name: Set IP Address
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      <<: *vm_login
      vm_password: '{{ vm_password_old }}'
      vm_shell: '/usr/bin/sh'
      vm_shell_args: "-c \"nmcli connection modify ens32 IPv4.address {{vm_address}}/{{vm_netmask_cidr}} IPv4.gateway {{vm_gateway}} IPv4.method manual\""
      wait_for_process: true 
  - name: Set DNS
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      <<: *vm_login
      vm_password: '{{ vm_password_old }}'
      vm_shell: '/usr/bin/sh'
      vm_shell_args: "-c \"nmcli connection modify ens32 IPv4.dns {{vm_dns_server}}\""
      wait_for_process: true  
  - name: Set Admin Passwd
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      <<: *vm_login
      vm_password: '{{ vm_password_old }}'
      vm_shell: '/usr/bin/sh'
      vm_shell_args: "-c \"echo {{vm_password_new}} | passwd --stdin admin\""
      wait_for_process: true  
  - name: Set root Passwd
    local_action:
      module: vmware_vm_shell
      <<: *esxi_login
      <<: *vm_login
      vm_password: '{{ vm_password_old }}'
      vm_shell: '/usr/bin/sh'
      vm_shell_args: "-c \"echo {{vm_password_new}} | passwd --stdin root\""
      wait_for_process: true  
    ignore_errors: yes
  - name: Reboot-Guest
    vmware_guest_powerstate:
      <<: *esxi_login 
      name: '{{ vm_name }}'
      state: reboot-guest
    delegate_to: localhost
    register: deploy
  - name: Wait for 30 seconds
    wait_for: timeout=30
    delegate_to: localhost
  - name: Wait for VMware tools to become available by name
    vmware_guest_tools_wait:
      <<: *esxi_login
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Wait for 30 seconds for VMware Tools refresh
    wait_for: timeout=30
    delegate_to: localhost
  - name: Find the VM's IP Address via VMware tools
    vmware_guest_facts:
      <<: *esxi_login
      datacenter: ha-datacenter
      name: '{{ vm_name }}'
    delegate_to: localhost
    register: vmfacts
  - debug: msg="IP Address - {{ vmfacts['instance']['ipv4'] }}"   


