---
- hosts: localhost 
  name: Deploy ONTAP Simulator Single Node Cluster
  gather_facts: false
  vars:
    vsim_ova: './OVA/vsim-netapp-DOT9.8-cm_nodar.ova'
    vm_name: lab_ansible_v2_vsim1
    cluster_network: lab_ansible_v2_1
    data_network: lab_ansible_v2_1
    ontap_cluster_mgmt_ip: 192.168.0.70
    ontap_node_mgmt_ip: 192.168.0.71
    ontap_netmask: 255.255.255.0
    ontap_gateway: 192.168.0.1
    ontap_cluster_name: vsim
    ontap_password: P@ssw0rd
    ontap_dns_domain: lab.local
    ontap_dns_server: 192.168.0.1
    ontap_location: lab_ansible_v2
    esxi_datastore: lab_ansible_v2
    esxi_login: &esxi_login
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'   
      validate_certs: no 
    vm_login: &vm_login
      vm_username: "admin"
      vm_password: ''
      vm_id: '{{ vm_name }}'
    retry_settings: &retry_settings
      retries: 6
      delay: 10 
      register: result           
      until: result is succeeded   
  vars_files: 
    vars-esx.yml
  tasks:
  - vmware_deploy_ovf:
      <<: *esxi_login
#      datacenter: 'lab_ansible_v2'
#      cluster: '{{ vcenter_cluster }}'
      datastore: "{{esxi_datastore}}"
      name: "{{vm_name}}"
      ovf: "{{vsim_ova}}"
      disk_provisioning: thin
      power_on: no
      networks: "{u'hostonly':u'{{ cluster_network }}',u'nat':u'{{ data_network }}'}"
      wait_for_ip_address: false
    delegate_to: localhost
    retries: 10
    delay: 60
    register: result           
    until: result is succeeded 
  - name: Adjust VM Sizing
    vmware_guest:
      <<: *esxi_login
      name: '{{ vm_name }}'
      state: present
      hardware:
        memory_mb: 8192
  #       num_cpus: '{{ ontap_num_vcpus }}'
  #       memory_reservation_lock: true
  #       cpu_reservation: 1000 # ensure enough CPU to flush nvram when host is overloaded
  #     customvalues:
  #       - key: pciHole.start
  #         value: 1024  # Moving the PCI hole here gives ONTAP access to more system ram
    delegate_to: localhost
  - name: Start VM
    vmware_guest:
      <<: *esxi_login
      name: '{{ vm_name }}'
      state: poweredon
      wait_for_ip_address: false
    delegate_to: localhost
  - name: Wait for VMware tools to become available
    community.vmware.vmware_guest_tools_wait:
      <<: *esxi_login
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Reboot-Guest
    community.vmware.vmware_guest_powerstate:
      <<: *esxi_login 
      name: '{{ vm_name }}'
      state: reboot-guest
    delegate_to: localhost
    register: deploy
  - name: Wait for 30 seconds for VM Tools to stop
    wait_for: timeout=30
    delegate_to: localhost
  - name: Wait for VMware tools to become available
    community.vmware.vmware_guest_tools_wait:
      <<: *esxi_login
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Wait for 30 seconds for 2nd boot to complete
    wait_for: timeout=30
    delegate_to: localhost
  - name: Send a string to virtual machine
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "yes"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Node Management Interface Port
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "e0c"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
    register: keys_num_sent
  - name: Enter the Node Management IP Address
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_node_mgmt_ip}}"
    delegate_to: localhost
    register: keys_num_sent
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
    register: keys_num_sent
  - name: Enter the Node Management Netmask
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_netmask}}"
    delegate_to: localhost
    register: keys_num_sent
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
    register: keys_num_sent
  - name: Enter the Node Management Gateway
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_gateway}}"
    delegate_to: localhost
    register: keys_num_sent
  - name: Send a string to virtual machine
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
    register: keys_num_sent
  - name: Send a string to virtual machine
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Create New Cluster
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "create"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Set Password
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_password}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Retype the Password
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_password}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Cluster Name
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_cluster_name}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Wait 120 seconds for cluster setup
    wait_for: timeout=120
    delegate_to: localhost
  - name: Enter additional license keys
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: " "
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Cluster Management interface Port
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "e0c"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Cluster Management IP Address
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_cluster_mgmt_ip}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Cluster Management Netmask
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_netmask}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Cluster Management Default Gateway
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_gateway}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the DNS Domain Name
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_dns_domain}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Enter the Name Server IP Address
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_dns_server}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost
  - name: Where is the controller located
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      string_send: "{{ontap_location}}"
    delegate_to: localhost
  - name: Press Enter
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
    delegate_to: localhost






