---
- name: Create ONTAP VM - vsim2-01
  hosts: localhost
  gather_facts: false
  vars_files: 
    - vars/vars-esx.yml
    - defaults/ONTAPvsim.yml
  tasks:
    - name: Deploy an ONTAP vsim
      set_fact:
        vm_name: lab_ansible_v2_vsim181
        vm_datastore: lab_ansible_v2
        sys_serial_number: "4082368-50-7" 
        cluster_network: lab_ansible_v2_1
        data_network: lab_ansible_v2_1
        ontap_node_mgmt_ip: "192.168.0.181"
        ontap_netmask: "255.255.255.0"
        ontap_gateway: "192.168.0.1"
    - include_tasks: "tasks/DeployONTAPvsim.yml"

    - name: cluster setup
      set_fact:
        # These additional items are required by cluster setup
        vm_name: lab_ansible_v2_vsim181
        ontap_cluster_mgmt_ip: 192.168.0.180
        ontap_cluster_name: demo
        ontap_password: P@ssw0rd
        ontap_dns_domain: lab.local
        ontap_dns_server: 192.168.0.1
        ontap_location: "virtual_lab"
        ontap_netmask: "255.255.255.0"
        ontap_gateway: "192.168.0.1"
    - include_tasks: "tasks/ConfigureONTAPvsim.yml"
