---
- name: Build Lab - Ansible
  hosts: localhost
  gather_facts: false
  vars:
    lab_name: lab_ansible_v2
    lab_password: P@ssw0rd
    lab_network_wan_portgroup: "VM Network"
    lab_network_lan1_portgroup: "lab_ansible_v2_1"
    lab_network_lan2_portgroup: "lab_ansible_v2_2"
    lab_network_lan1_netmask_cidr: 24
    lab_network_lan1_netmask: "255.255.255.0"
    lab_network_lan1_gateway: "192.168.0.1"
    lab_network_lan1_dns_ip: "192.168.0.1"
    lab_domain_name: "lab.local"
    lab_dc01_ip: "192.168.0.11"
    lab_win1_ip: "192.168.0.12"
    lab_ansible_ip: "192.168.0.13"
    lab_centos1_ip: "192.168.0.15"
    lab_vsim1_cluster_mgmt_ip: "192.168.0.80"
    lab_vsim1_node_mgmt_ip: "192.168.0.81"
    lab_vsim2_01_node_mgmt_ip: "192.168.0.91"
    lab_vsim2_02_node_mgmt_ip: "192.168.0.92"
    lab_vsim1_cluster_name: "vsim1"
    lab_vm_datastore: lab_ansible_v2
#    skip_gateway_vm: true
#    skip_dc01_vm: true
#    skip_win1_vm: true
#    skip_ansible_vm: true
#    skip_centos1_vm: true
#    skip_vsim1_vm: true
#    skip_vsim2_01_vm: true
#    skip_vsim2_02_vm: true
  vars_files: 
    - vars/vars-esx.yml
  tasks:
    - name: Build lab pfSense Gateway
      meta: noop
    - block:
      - include_vars: defaults/Build_pfSense_from_ISO.yml
      - set_fact:
          vm_name: '{{lab_name}}_gateway'
          vm_datastore: "{{lab_vm_datastore}}"
          vm_password_new: "{{lab_password}}"
          vm_network_wan: "{{lab_network_wan_portgroup}}"
          vm_network_lan: "{{lab_network_lan1_portgroup}}"
          config_xml_file: "files/pfsense/config.xml"
      - include_tasks: tasks/Build_pfSense_from_ISO.yml
      when: skip_gateway_vm is not true

    - name: Build Windows VM - DC01
      meta: noop
    - block:
      - include_vars: defaults/Build_Windows_VM_from_ISO.yml
      - set_fact:
          vm_name: '{{lab_name}}_dc01'         
          vm_datastore: "{{lab_vm_datastore}}"
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_password_new: "{{lab_password}}"
          vm_hostname: dc01        
          vm_address: "{{lab_dc01_ip}}"
          vm_netmask_cidr: "{{lab_network_lan1_netmask_cidr}}"
          vm_gateway: "{{lab_network_lan1_gateway}}"
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
      - include_tasks: tasks/Build_Windows_VM_from_ISO.yml
      when: skip_dc01_vm is not true

    - name: Build a Active Directory Forest
      meta: noop
    - block:
      - set_fact:
          vm_name: '{{lab_name}}_dc01'
          vm_username: ".\\Administrator" 
          vm_password: "{{lab_password}}"         
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
      - include_tasks: tasks/Create_New_Active_Directory_using_vm_shell.yml
      when: skip_dc01_vm is not true    

    - name: Build Windows VM - WIN1
      meta: noop
    - block:
      - include_vars: defaults/Build_Windows_VM_from_ISO.yml
      - set_fact:
          vm_hostname: win1        
          vm_name: '{{lab_name}}_win1'
          vm_address: "{{lab_win1_ip}}"                 
          vm_datastore: "{{lab_vm_datastore}}"
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_password_new: "{{lab_password}}"
          vm_netmask_cidr: "{{lab_network_lan1_netmask_cidr}}"
          vm_gateway: "{{lab_network_lan1_gateway}}"
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
      - include_tasks: tasks/Build_Windows_VM_from_ISO.yml
      when: skip_win1_vm is not true

    - name: Build CentOS VM - ansible
      meta: noop
    - block:
      - include_vars: defaults/Build_CentOS8_VM_from_ISO.yml
      - set_fact:
          vm_hostname: ansible
          vm_address: "{{lab_ansible_ip}}"       
          vm_name: '{{lab_name}}_ansible'
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_password_new: "{{lab_password}}"
          vm_netmask_cidr: "{{lab_network_lan1_netmask_cidr}}"
          vm_gateway: "{{lab_network_lan1_gateway}}"
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
          vm_datastore: "{{lab_vm_datastore}}"
      - include_tasks: tasks/Build_CentOS8_VM_from_ISO.yml
      when: skip_ansible_vm is not true

    - name: Build CentOS VM - centos1
      meta: noop
    - block:
      - include_vars: defaults/Build_CentOS8_VM_from_ISO.yml
      - set_fact:
          vm_hostname: centos1
          vm_address: "{{lab_centos1_ip}}"       
          vm_name: '{{lab_name}}_centos1'
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_password_new: "{{lab_password}}"
          vm_netmask_cidr: "{{lab_network_lan1_netmask_cidr}}"
          vm_gateway: "{{lab_network_lan1_gateway}}"
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
          vm_datastore: "{{lab_vm_datastore}}"
      - include_tasks: tasks/Build_CentOS8_VM_from_ISO.yml
      when: skip_centos1_vm is not true


    - name: Build ONTAP Simulator - vsim1
      meta: noop
    - block:
      - include_vars: defaults/Build_ONTAP_Simulator_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_vsim1'
          vm_datastore: "{{lab_vm_datastore}}"
          sys_serial_number: "4082368-50-7" 
          cluster_network: "{{lab_network_lan1_portgroup}}"
          data_network: "{{lab_network_lan1_portgroup}}"
          ontap_node_mgmt_ip: "{{lab_vsim1_node_mgmt_ip}}"
          ontap_netmask: "{{lab_network_lan1_netmask}}"
          ontap_gateway: "{{lab_network_lan1_gateway}}"
      - include_tasks: "tasks/Build_ONTAP_Simulator_from_OVA.yml"

      - name: Run Cluster Setup on vsim1
        set_fact:
          # These additional items are required by cluster setup
          vm_name: '{{lab_name}}_vsim1'
          ontap_cluster_mgmt_ip: "{{lab_vsim1_cluster_mgmt_ip}}"
          ontap_cluster_name: "{{lab_vsim1_cluster_name}}"
          ontap_password: "{{lab_password}}"
          ontap_dns_domain: "{{lab_domain_name}}"
          ontap_dns_server: "{{lab_network_lan1_dns_ip}}"
          ontap_location: "{{lab_name}}"
          ontap_netmask: "{{lab_network_lan1_netmask}}"
          ontap_gateway: "{{lab_network_lan1_gateway}}"
      - include_tasks: "tasks/Run_Cluster_Setup_from_vm_shell.yml"
      when: skip_vsim1_vm is not true

    - name: Build ONTAP Simulator - vsim2-01
      meta: noop
    - block:
      - include_vars: defaults/Build_ONTAP_Simulator_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_vsim2-01'
          vm_datastore: "{{lab_vm_datastore}}"
          sys_serial_number: "4082368-50-7" 
          cluster_network: "{{lab_network_lan2_portgroup}}"
          data_network: "{{lab_network_lan1_portgroup}}"
          ontap_node_mgmt_ip: "{{lab_vsim2_01_node_mgmt_ip}}"
          ontap_netmask: "{{lab_network_lan1_netmask}}"
          ontap_gateway: "{{lab_network_lan1_gateway}}"
      - include_tasks: "tasks/Build_ONTAP_Simulator_from_OVA.yml"
      when: skip_vsim2_01_vm is not true

    - name: Build ONTAP Simulator - vsim2-02
      meta: noop
    - block:
      - include_vars: defaults/Build_ONTAP_Simulator_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_vsim2-02'
          vm_datastore: "{{lab_vm_datastore}}"
          sys_serial_number: "4034389-06-2" 
          cluster_network: "{{lab_network_lan2_portgroup}}"
          data_network: "{{lab_network_lan1_portgroup}}"
          ontap_node_mgmt_ip: "{{lab_vsim2_02_node_mgmt_ip}}"
          ontap_netmask: "{{lab_network_lan1_netmask}}"
          ontap_gateway: "{{lab_network_lan1_gateway}}"
      - include_tasks: "tasks/Build_ONTAP_Simulator_from_OVA.yml"
      when: skip_vsim2_02_vm is not true

