---
- hosts: localhost 
  name: Deploy ONTAP Simulator Single Node Cluster
  gather_facts: false
  vars:
    vsim_ova: './OVA/vsim-netapp-DOT9.8-cm_nodar.ova'
    vm_name: lab_ansible_v2_vsim1
    cluster_network: lab_ansible_v2_1
    data_network: lab_ansible_v2_1
    ontap_cluster_mgmt_ip: 192.168.0.70
    ontap_node_mgmt_ip: 192.168.0.71
    ontap_netmask: 255.255.255.0
    ontap_gateway: 192.168.0.1
    ontap_cluster_name: vsim
    ontap_password: P@ssw0rd
    ontap_dns_domain: lab.local
    ontap_dns_server: 192.168.0.1
    ontap_location: lab_ansible_v2
    esxi_datastore: lab_ansible_v2
    esxi_login: &esxi_login
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'   
      validate_certs: no  
  # vars_files: 
  #   vars-vsim1.yml
  #   vars-esx.yml
  tasks:
  - name: Start VM
    vmware_guest:
      <<: *esxi_login
      name: '{{ vm_name }}'
      state: poweredon
      wait_for_ip_address: false
    delegate_to: localhost
  - name: Wait for VMware tools to become available
    community.vmware.vmware_guest_tools_wait:
      <<: *esxi_login
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Reboot-Guest #this is to help ensure we land at the setup script
    community.vmware.vmware_guest_powerstate:
      <<: *esxi_login 
      name: '{{ vm_name }}'
      state: reboot-guest
    delegate_to: localhost
    register: deploy
  - name: Wait for 30 seconds for VM Tools to stop
    wait_for: timeout=30
    delegate_to: localhost
  - name: Wait for VMware tools to become available
    community.vmware.vmware_guest_tools_wait:
      <<: *esxi_login
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Wait for 60 seconds for 2nd boot to complete
    wait_for: timeout=60
    delegate_to: localhost
  - name: Complete interactive setup
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
      string_send: "{{item}}"
    delegate_to: localhost
    loop: 
      - "yes"
      - "e0c" # node mgmt port
      - "{{ontap_node_mgmt_ip}}"
      - "{{ontap_netmask}}"
      - "{{ontap_gateway}}"
      - " " # this completes the node setup phase
      - "create" # operation create|join
      - "no" # single node cluster yes|no
      - "yes" # use default cluster lif configuration
      - "{{ontap_password}}"
      - "{{ontap_password}}" # confirm password
      - "{{ontap_cluster_name}}"
      - "" # this final space is here to force the enter key after the preceding command

  - name: Wait 120 seconds for cluster setup
    wait_for: timeout=120
    delegate_to: localhost

  - name: Complete interactive setup
    community.vmware.vmware_guest_sendkey:
      <<: *esxi_login
      name: "{{ vm_name }}"
      keys_send: ENTER
      string_send: "{{item}}"
    delegate_to: localhost
    loop: 
      - " " # Enter additional license keys
      - "e0c" # cluster mgmt port
      - "{{ontap_cluster_mgmt_ip}}"
      - "{{ontap_netmask}}"
      - "{{ontap_gateway}}"
      - "{{ontap_dns_domain}}" 
      - "{{ontap_dns_server}}"
      - "{{ontap_location}}" # single node cluster yes|no
      - " " # this final space is here to force the enter key after the preceding command








