---
- hosts: localhost
  tasks:
    - name: Create Centos8 kickstart ISO
      community.general.iso_create:
        src_files:
          - ./OEMDRV/ks.cfg
        dest_iso: ./Centos8-ks.iso
        interchange_level: 3
        joliet: 3
        vol_ident: OEMDRV
    - name: Query a file on a datastore
      community.vmware.vsphere_file:
        host: '192.168.123.49'
        username: 'root'
        password: 'P@ssw0rd'
        validate_certs: no
        datacenter: ""
        datastore: AdminISO
        path: CentOS-8.3.2011-x86_64-dvd1.iso
        state: file
      register: iso_exists
      delegate_to: localhost
      ignore_errors: true
    - name: Copy file to datastore using delegate_to
      community.vmware.vsphere_copy:
        hostname: '192.168.123.49'
        username: 'root'
        password: 'P@ssw0rd'
        validate_certs: no
        src: ./CentOS-8.3.2011-x86_64-dvd1.iso
#        datacenter: DC1 Someplace
        datastore: AdminISO
        path: CentOS-8.3.2011-x86_64-dvd1.iso
      delegate_to: localhost
      when: iso_exists.failed
    - name: Query a file on a datastore
      community.vmware.vsphere_file:
        host: '192.168.123.49'
        username: 'root'
        password: 'P@ssw0rd'
        validate_certs: no
        datacenter: ""
        datastore: AdminISO
        path: CentOS-8.3.2011-x86_64-dvd1.iso
        state: file
      register: iso_exists
      delegate_to: localhost
      ignore_errors: true
