---
- name: Start VM
  vmware_guest:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'   
    validate_certs: no  
    name: '{{ vm_name }}'
    state: poweredon
    wait_for_ip_address: false
  delegate_to: localhost
- name: Wait for VMware tools to become available
  community.vmware.vmware_guest_tools_wait:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'   
    validate_certs: no  
    name: '{{ vm_name }}'
  delegate_to: localhost
  retries: 3
  delay: 15
  register: result           
  until: result is succeeded 
- name: Reboot-Guest #this is to help ensure we land at the setup script
  community.vmware.vmware_guest_powerstate:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'   
    validate_certs: no   
    name: '{{ vm_name }}'
    state: reboot-guest
  delegate_to: localhost
  register: deploy
- name: Wait for 30 seconds for VM Tools to stop
  wait_for: timeout=30
  delegate_to: localhost
- name: Wait for VMware tools to become available
  community.vmware.vmware_guest_tools_wait:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'   
    validate_certs: no  
    name: '{{ vm_name }}'
  delegate_to: localhost
  retries: 3
  delay: 15
  register: result           
  until: result is succeeded 
- name: Wait for 60 seconds for 2nd boot to complete
  wait_for: timeout=60
  delegate_to: localhost
- name: Complete interactive setup
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'   
    validate_certs: no  
    name: "{{ vm_name }}"
    keys_send: ENTER
    string_send: "{{item}}"
  delegate_to: localhost
  loop: 
    - "yes"
    - "e0c" # node mgmt port
    - "{{ontap_node_mgmt_ip}}"
    - "{{ontap_netmask}}"
    - "{{ontap_gateway}}"
    - " " # this completes the node setup phase
    - "create" # operation create|join
    - "no" # single node cluster yes|no
    - "yes" # use default cluster lif configuration
    - "{{ontap_password}}"
    - "{{ontap_password}}" # confirm password
    - "{{ontap_cluster_name}}"
    - "" # This is here to force the enter key to be pressed
- name: Wait 120 seconds for cluster setup
  wait_for: timeout=120
  delegate_to: localhost

- name: Complete interactive setup
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ esxi_address }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'   
    validate_certs: no  
    name: "{{ vm_name }}"
    keys_send: ENTER
    string_send: "{{item}}"
  delegate_to: localhost
  loop: 
    - "e0c" # cluster mgmt port
    - "{{ontap_cluster_mgmt_ip}}"
    - "{{ontap_netmask}}"
    - "{{ontap_gateway}}"
    - "{{ontap_dns_domain}}" 
    - "{{ontap_dns_server}}"
    - "{{ontap_location}}" # single node cluster yes|no
    - "" # this is here to force the enter key after the preceding command








